#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/Stock?createDatabaseIfNotExist=true
#    username: root
#    password: Esteem@12?
#    initialization-mode: always
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    ddl-auto: update